FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
# Aponta para o teste de carga
RUN CGO_ENABLED=0 GOOS=linux go build -o app-exec ./cmd/TesteCarga

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/app-exec .
ENTRYPOINT ["./app-exec"]
